#!/bin/bash
VERSION="1.1.0"

#USAGE="Usage: myssh <connection> \n"
#USAGE+=	"wormulon \t- Uidaho cs machine\n"
#USAGE+=	"openhab \t- Home automation pi"
#	ubuntu \t\t- Nick@ubuntu\n
#	minecraft \t- minecraft@ubuntu\n
#	brad \t\t- brad@bradsUbuntu"
#	-help \t\t- Prints this menue
#	-version \t- Prints version"


#http://stackoverflow.com/questions/23929235/multi-line-string-with-extra-space-preserved-indentation
USAGE=$(cat <<-END
    wormulon \t- Uidaho cs machine
    openhab \t- Home automation pi
    ubuntu \t- Nick@ubuntu
    minecraft \t- minecraft@ubuntu
    -help \t- Prints this menu
    -version \t- Prints version
END
)
	
	
# no arguments supplied. print usage & exit
if [ $# == 0 ] ; then
    echo -e "$USAGE"
    exit 1;
fi

case $1 in
	wormulon)
		ssh kren5141@wormulon.cs.uidaho.edu
		;;
	openhab)
		ssh pi@leagueofsao.ddns.net -p 10008
		;;
	ubuntu)
		ssh nick@leagueofsao.ddns.net -p 23
		;;
	minecraft)
		ssh minecraft@leagueofsao.ddns.net -p 23
		;;
	brad)
		ssh -p 10007 brad@leagueofsao.ddns.net
		;;
	-help)
		echo -e "$USAGE"
		;;
	-version)
		echo $VERSION
		;;
	*)
		echo "Not understood"
		echo -e "$USAGE"
		;;
esac
